_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.7
            "5": 0.18.3
            "6": 4.42.4
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
